version: '3.8'

services:
  areyoutravelers:
    build: .
    image: areyoutravelers:latest
    container_name: areyoutravelers
    ports:
      - "8080:8080"
    environment:
      SPRING_REDIS_HOST: redis
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
