version: '3.8'

services:
  areyoutravelers:
    image: areyoutravelers
    build: .
    container_name: areyoutravelers
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"